0 set time-pos 0
9 set speed 1
RIGHT seek  5
LEFT  seek -5
a seek  -60
s seek  60
LEFT  seek -5
UP    add volume 5
DOWN  add volume -5
] add speed 0.1
[ add speed -0.1
} add speed 0.5
{ add speed -0.5
p show-text '${playlist-pos-1}/${playlist-count} ${media-title}'
) set playlist-pos 0
CTRL+c stop
