return {
  -- 'nvim-lualine/lualine.nvim',
  -- cmd = "Lualine",
  -- config = function()
  --   require('lualine').setup {
  --     options = {
  --       icons_enabled = true,
  --       theme = 'tomorrow_night',
  --       component_separators = { left = '', right = '' },
  --       section_separators = { left = '', right = '' },
  --       disabled_filetypes = {
  --         statusline = {},
  --         winbar = {},
  --       },
  --       ignore_focus = {},
  --       always_divide_middle = true,
  --       globalstatus = false,
  --       refresh = {
  --         statusline = 100,
  --         tabline = 100,
  --         winbar = 100,
  --       }
  --     },
  --     sections = {
  --       lualine_a = { 'mode' },
  --       lualine_b = { 'filename' },
  --       lualine_c = {},
  --       lualine_x = {},
  --       lualine_y = {},
  --       lualine_z = {}
  --     },
  --     inactive_sections = {
  --       lualine_a = {},
  --       lualine_b = {},
  --       lualine_c = { 'filename' },
  --       lualine_x = {},
  --       lualine_y = {},
  --       lualine_z = {}
  --     },
  --     tabline = {},
  --     winbar = {},
  --     inactive_winbar = {},
  --     extensions = {}
  --   }
  -- end
}
