general.import = [
    "~/.config/alacritty/window.toml",
    "~/.config/alacritty/font.toml",
    "~/.config/alacritty/others.toml",
    "~/.config/alacritty/scrolling.toml",
    "~/.config/alacritty/colors.toml",
    # "~/.config/alacritty/github/github_dark.toml",
    #"~/.config/alacritty/rose-pine/rose-pine-frappe.toml",
    "~/.config/alacritty/kanagawa/kanagawa_dragon.toml",
]

